### ISSUE TITLE
the  side panel background color problem

### ISSUE THREAD

**Issue by czmecho** [YuichiNukiyama/vscode-preview-server#10]
can you provide a setting that i can set the side panel background color so that i can use my favorite theme.
https://ws1.sinaimg.cn/large/7df5111fgy1ffnbei0x18j20gh0bvt8p.jpg

https://ws1.sinaimg.cn/large/7df5111fgy1ffnbei9a9zj20m80ibwf8.jpg

https://ws1.sinaimg.cn/large/7df5111fgy1ffnbei5txaj20qb0jtjry.jpg

**Comment by YuichiNukiyama** [comment]
If you want to change background color for side panel, you shoud set css background-color property to body tag.

**Comment by czmecho** [comment]
@YuichiNukiyama  yes, I can set css background-color property in the html file.
but in this way ,I have to set the css  background-color property  every time when I create a new file.

while the white color is the default color background color in browser,maybe use the white color as the side panel default background color is a better choice.

**Comment by YuichiNukiyama** [comment]
I see. I set default background-color. a35c34370be14bafbe67d49ffb2755db9d084288

**Comment by czmecho** [comment]
@YuichiNukiyama thanks.

**Comment by YuichiNukiyama** [comment]
Anytime!
