### ISSUE TITLE
Cannot GET Issue

### ISSUE THREAD

**Issue by ferdyanata** [YuichiNukiyama/vscode-preview-server#13]
Hi it's been working fine for the first few days then suddenly i'm getting this problem. I'm on windows by the way.

http://imgur.com/9zrAi1x

**Comment by YuichiNukiyama** [comment]
Maybe, you might open file with "**open file**".
Version 0.7 support file with "**open file**". Please try it 😄

**Comment by ferdyanata** [comment]
I figured out the issue. You need to go to File > Open Folder [Ctrl + K Ctrl + O]. I think the reason is that it needs to be an entire folder not just one file. @YuichiNukiyama unless this is what you meant. 'Open File' doesn't work.

**Comment by Sh1noka** [comment]
I also encounter this problem. Please consider giving a proper error message.

**Comment by YuichiNukiyama** [comment]
@Sh1noka 
Thanks for your feedback. This is closed issue. So, I open new one(#33).

**Comment by ladychili** [comment]
I have the same problem when open as a workspace.
