### ISSUE TITLE
Support for changing default browser

### ISSUE THREAD

**Issue by Nil-Zil** [YuichiNukiyama/vscode-preview-server#14]
It is a good extension! But currently I found that it can only run in the browser as system default. Could you please add an option for changing default browser? Thanks!

**Comment by YuichiNukiyama** [comment]
This extension use browser-sync. And browser-sync has [browser option](https://www.browsersync.io/docs/options#option-browser). So, We can do it.

**Comment by Nil-Zil** [comment]
That will be good, thanks!

**Comment by Nil-Zil** [comment]
Hello, how is the progress?

**Comment by YuichiNukiyama** [comment]
sorry for my delay.
I try it. But I can not change default browser.
Because this extension use [vscode.open option](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) for launch browser, but this option do not support changing browser.

**Comment by YuichiNukiyama** [comment]
Now we can change default browser (https://github.com/YuichiNukiyama/vscode-preview-server/commit/bc43a01d743af4fcd754da6ecf2ee5d510c4686b).
Please try new version. [Setting example](https://marketplace.visualstudio.com/items?itemName=yuichinukiyama.vscode-preview-server#user-content-example).

**Comment by YuichiNukiyama** [comment]
If there is anothor problem, please open new issue.
