### ISSUE TITLE
Question: How to change settings

### ISSUE THREAD

**Issue by aresares** [YuichiNukiyama/vscode-preview-server#20]
HI how can I change port from 8080 to 4200. I want to listen to angular4 server

Thanks

**Comment by YuichiNukiyama** [comment]
You can use port option. See following example:

```
{
    "previewServer.proxy": "http://localhost:8080/",   // Listen Angular server.
    "previewServer.port":  4200,                                  // Change Port number of Preview Server.
}
```

**Comment by aresares** [comment]
yes ok but I cannot change settings, cannot find settings/configuration file.
I looked her but nothing

![immagine](https://user-images.githubusercontent.com/15111793/32542657-9413f9ce-c473-11e7-904b-fb7331659e70.png)

**Comment by YuichiNukiyama** [comment]
Extension settings can be made in the same file as VS Code setting.
So, the menu command File > Preferences > Settings provides entry to configure user and workspace settings.

**Comment by aresares** [comment]
OK thanks I solved
