### ISSUE TITLE
How to figure out what folder to serve when using a VS Code workspace

### ISSUE THREAD

**Issue by YuichiNukiyama** [YuichiNukiyama/vscode-preview-server#21]
move from https://github.com/YuichiNukiyama/vscode-preview-server/issues/18#issuecomment-353647283

Related: this extension cannot figure out what folder to serve when using a VS Code workspace. It always defaults to the project folder of the first project. I'm posting this here because the solution for the stated problem needs to address both issues.

**Comment by YuichiNukiyama** [comment]
@jmussman
You can change folder with using `stratupProject` option.
In this sample, the extension is rooted in the Test folder.

```json
{
    "previewServer.stratupProject": "Test"
}
```

```json :sample.code-workspace
{
	"folders": [
		{
			"name": "Product",
			"path": "foo"
		},
		{
                        "name": "Test",
			"path": "bar"
		}
	],
	"settings": {
		"previewServer.startupProject": "Product"
	}
}
```

**Comment by jmussman** [comment]
Hi Yuichi,

I think that’s my bad. I just copied the code, and startup is spelled wrong in the documentation ☺

Thanks!
Joel

**Comment by YuichiNukiyama** [comment]
Sorry for my typo. I just fixed it. https://github.com/YuichiNukiyama/vscode-preview-server/commit/8b72ba5736bf6a2c5ef2e81cccd2442ba62d722d
