### ISSUE TITLE
Most of the time it works, but sometimes it doesn't

### ISSUE THREAD

**Issue by Madebym** [YuichiNukiyama/vscode-preview-server#22]
As the title says. 95% of the time it works, but sometimes it just fires up new Chrome windows.

A few times a simple restart of VS Code did the trick, but that doesn't help anymore.

If I hit `ctrl + shift + l`, it just opens a new blank Chrome window. If I hit it again, I get another window. 

I am on Mac OS High Sierra 10.13.2.

p.s. I tried switching default browser, ignoring it. Nothing helps, funny thing is if I switch default browser, then it doesn't even load new blank window like in Chrome.

**Comment by Madebym** [comment]
I restarted my mac, and the live preview is working fine again. 

I am sorry I can't be of any help, this is happening randomly. With VS Code and OS reload the only remedy I found.

**Comment by YuichiNukiyama** [comment]
Please report again as you know the details 😄
