### ISSUE TITLE
Gui Button and Notification Message

### ISSUE THREAD

**Issue by saileshkush95** [YuichiNukiyama/vscode-preview-server#27]
This plugins works fine but actually I want GUI button for starting server as well as starting side by side preview. And also please add the features for disabling messages showing each and every times when after refreshing.

**Comment by YuichiNukiyama** [comment]
56b71d968e5718affd6a5aeb9a28be3ac9d203a4

**Comment by YuichiNukiyama** [comment]
I release 1.1.0
