### ISSUE TITLE
Doesn't launch any web browser

### ISSUE THREAD

**Issue by neildobson-au** [YuichiNukiyama/vscode-preview-server#31]
I've been using this extension at home and it works really well, but on my work machine it doesn't do anything.

I've installed VS Code x64 v1.27.2 (user setup). When I right-click my html file it doesn't launch any browser or add a tab to an open browser. When I open the HTML file and then type Ctrl-Shift-L I get an alert saying command 'extension.launch' not found.

I've tried uninstalling and removing the yuichinukiyama.vscode-preview-server-1.1.0 folder

I have 3 other extensions (non web related) all working fine. I tried without any configuration and with the sample configuration.

**Comment by tb30579kaw** [comment]
Me too. I already reinstall vscode and extension,but mistake still not disappear.

Thanks.
Version: VS Code X64 1.27.2

**Comment by Morningstar1217** [comment]
一样遇到了这个问题  感觉很蛋疼啊。。这下咋搞

**Comment by LuniaMage** [comment]
The extension isn't working for me either. I keep getting command 'extension.preview' and 'extension.launch' not found. I've uninstalled and reinstalled in VS code.

**Comment by jmaties** [comment]
same error, I already reinstall vscode and extension,but mistake still not disappear.
Version: OSX Versión 1.27.2 (1.27.2)

**Comment by Morningstar1217** [comment]
我现在用的是live server，可以达到一样的效果




------------------ 原始邮件 ------------------
发件人: "Javier Maties"<notifications@github.com>;
发送时间: 2018年9月25日(星期二) 下午4:45
收件人: "YuichiNukiyama/vscode-preview-server"<vscode-preview-server@noreply.github.com>;
抄送: "祝兆庆"<2702155238@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [YuichiNukiyama/vscode-preview-server] Doesn't launch any webbrowser (#31)




same error, I already reinstall vscode and extension,but mistake still not disappear.
 Version: OSX Versión 1.27.2 (1.27.2)

**Comment by ShivalThakur** [comment]
It is not working on my machine too having VS Code :
Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

But it was working yesterday.

**Comment by rlkee888** [comment]
There is an issue with gulp used in the dependencies

**Comment by ShivalThakur** [comment]
Yesterday I ran CCleaner on my system. When I use toggle developer tools of VS Code, I came to know that the extension was missing 'opener' module. I opened extension folder and run npm install -g, got some errors but the extension is working fine now.

Thanks.

**Comment by YuichiNukiyama** [comment]
Sorry, I failed to publish. I publish new version.
Thank you for your reports and investigations 😄

**Comment by JoeSchiaffi** [comment]
> Yesterday I had run CCleaner on my system. When I use toggle developer tools of VS Code, I came to know that the extension was missing 'opener' module. I opened extension folder and run npm install -g, got some errors but the extension is working fine now.
> 
> Thanks.

Hi there, had the same problem after a CCleaner task on my machine, can't get Live on Preview Server to work, could you please explain a little bit more in detail how did you fix the problem? Thanks
