### ISSUE TITLE
Don't use ctrl+shift+p as default keyboard shortcut

### ISSUE THREAD

**Issue by carlin-q-scott** [YuichiNukiyama/vscode-preview-server#36]
Visual Studio Code has ctrl+shift+p bound to the quick command pallet. I don't think any plugin should override this default, especially considering that it's used for the same thing in Visual Studio as well.

**Comment by YuichiNukiyama** [comment]
@carlin-q-scott 
Thanks for your feedback.
Actually I don't use this shortcut. Do you think what kind of shortcut is good?

**Comment by carlin-q-scott** [comment]
I switched the shortcut to ctrl+shift+v, mostly because the sidebar preview shortcut is ctrl+k,v. I guess v is for View.

**Comment by YuichiNukiyama** [comment]
I modified the shortcut and published new version.
