### ISSUE TITLE
Extension fail to work after vscode update 1.37.0

### ISSUE THREAD

**Issue by BurningUnder** [YuichiNukiyama/vscode-preview-server#42]
**Extension fail to work after I update vscode to 1.37.0  in 2019/08/08 .
Everytime I use preview command vscode will alert "command 'extension.preview' not found ".
Others commands fail to work too.
I had reboot vscode and try to uninstall and install again but it doesn't help.**

**Comment by Phillipus** [comment]
Same here.

**Comment by bree006** [comment]
Same for me. I've checked it before updating it works fine. Direct after updating and restarting vscode it is not working anymore.

**Comment by PGama-Rodrigo** [comment]
Same for me. I updated npm and nodeJS just to make sure everything is running on latest version. I use Windows 10 Pro.

**Comment by SoberK** [comment]
me too, please check the plugins

**Comment by yuwensaf** [comment]
Same here. I've tried to reinstall vs code and the extension, but the preview function still doesn't work at all. Every time I press 'ctrl + shift + l', vs code keeps showing this alert "command 'extension.launch' not found".   (I've checked my keyboard shortcuts, and it doesn't have any problems or conflicts)

**Comment by YuichiNukiyama** [comment]
Hi, everyone
Thanks for your reports. I tried to release bug fix version.
Please update your extension.

3d93d6a1e000c0bc18ec2de1953e232a64368019

**Comment by bree006** [comment]
Hi Yuichi,
I've updated the extension and it works fine again. Thank you for your quick repair!!

**Comment by Phillipus** [comment]
I can confirm it working again. Many thanks! :-)

**Comment by yuwensaf** [comment]
Hi Yuichi, I've just updated and it's now working perfectly! Thank you so much : )
