### ISSUE TITLE
Having an Issue Trying to live Preview

### ISSUE THREAD

**Issue by DavidAGullo** [YuichiNukiyama/vscode-preview-server#47]
whenever I try to use any of the shortcuts such ctrl + shift + v, it says extension not found, I updated everything node.js, npm, etc. but it works flawlessly on my other pc.

**Comment by TheDefinitionist** [comment]
Same here, on my lappy it works and on another account of this pc it works fine too, just not here, its weird. Got everything up to date and reinstalled still same issue.
