### ISSUE TITLE
No live reload feature.

### ISSUE THREAD

**Issue by freMea** [YuichiNukiyama/vscode-preview-server#5]
Hi,

- VS Code : 1.10.2
- Preview on Web Server: 0.3.1
- OS : Windows 10 PRO x64

The server starts and the page is rendered in browser or in side panel but the live reload feature won't work: editing and saving the .html file or the CSS and JS attached won't auto reload the page.

Note that my global BrowserSync install will work perfectly with live reload when I run with such a command:
`browser-sync start --server --files "*.css, *html, *.js" `

The extension have poor interest without the live reload. Maybe you can use embed BrowserSync and play with its API.

Regards

**Comment by YuichiNukiyama** [comment]
@freMea 
Thanks for your good idea. I add auto reload feature with this commit (https://github.com/YuichiNukiyama/vscode-preview-server/commit/9302d738caa5e95c38bcbfdab83f2dc1012eb665). And I released 0.4.0. Please try it!
