### ISSUE TITLE
How to set a shortcut key

### ISSUE THREAD

**Issue by jing2si** [YuichiNukiyama/vscode-preview-server#6]
All in title.

**Comment by YuichiNukiyama** [comment]
I added shortcut keys (https://github.com/YuichiNukiyama/vscode-preview-server/commit/7411c917fc6acad236d6694f492384fb82b0de22).
Overwrite it if it is difficult to use.

**Comment by jing2si** [comment]
@YuichiNukiyama How do I define my own shortcuts?
