### ISSUE TITLE
Cannot GET Error Message

### ISSUE THREAD

**Issue by ProjectPort** [YuichiNukiyama/vscode-preview-server#60]
I am receiving the error message "Cannot GET /d%3A%5CTemp%5CBoilerplate.html" when I try to display the web page for my code in VS Code with the keyboard shortcut ctrl+shift+v. I get the same error error message when using ctrl+shift+l. With ctrl+shift+l the web page opens at http://localhost:8080/d:%5CTemp%5CBoilerplate.html but the only thing being displayed is the same error message.

The file being edited has been saved and is at the location specified in the error message. I am using a very simple boilerplate.html file to demonstrate the error (attached as a ZIP). There are no user settings for this extension in setting.json specific to this extension. I have successfully stopped the web server and started it again - but the same error appears after it is restarted.

Preview On Web Server is at version v1.3.0. Other software levels:
VS Code Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

This extension was working normally two days ago and as far as I know I have made no system changes since that time.

[Boilerplate.zip](https://github.com/YuichiNukiyama/vscode-preview-server/files/5391447/Boilerplate.zip)
![Cannot GET Error Message](https://user-images.githubusercontent.com/10326573/96257730-7f3f0880-0f80-11eb-97da-490df0aeb7bd.jpg)

**Comment by ProjectPort** [comment]
I made no changes - not even a boot - since I submitted this but the problem has "gone away." So if someone did something on the code end of this extension...thank you. The problem has gone away and the extension is working normally. Closing the issue.

**Comment by ProjectPort** [comment]
I made no changes - not even a boot - since I submitted this but the problem has "gone away." So if someone did something on the code end of this extension...thank you. The problem has gone away and the extension is working normally. Closing the issue.

**Comment by ProjectPort** [comment]
This issue has now re-appeared (again, with no known changes made) so I have re-opened the issue. To be clear, the html file opens normally in VS Code. The location of the html file vscode-preview-server says it cannot find is:
D:\Temp\Boilerplate.html

**Comment by ProjectPort** [comment]
Issue was caused by a very hard to find virus that was specifically targeting file names in VS Code. Once removed, the problem disappeared. By the way, the virus came in with a copy of chkflsh.exe

**Comment by dobell733** [comment]
I'm having this same issue, any idea how to remove/find the virus that causes it?
