### ISSUE TITLE
This plugin conflict with the vim plugin

### ISSUE THREAD

**Issue by jing2si** [YuichiNukiyama/vscode-preview-server#9]
### Environment
VSCode: 1.12.1
OS: windows 10
Vim: 0.7.0
Preview on Web Server: 0.6.0

### Reproducible steps
When i toggle **NORMAL MODE** and **INSERT MODE** will trigger 'Resume the Web Server'

![1](https://cloud.githubusercontent.com/assets/2288824/25832532/b0d6c2f0-349d-11e7-97d7-d31d26bee413.gif)

### Reason
This my vim settings, when i toggle vim mode,  this settings  will dynamic change `settings.json` file, then will trigger you plugin show 'Resume the Web Server'
```
"vim.statusBarColorControl": true,
"vim.statusBarColors": {
  "normal": "#268bd2",
  "insert": "#d33682",
  "visual": "#268bd2",
  "visualline": "#2aa198",
  "visualblock": "#859900",
  "replace": "#b58900"
},
"workbench.colorCustomizations": {
  "statusBar.background": "#2aa198",
  "statusBar.noFolderBackground": "#2aa198",
  "statusBar.debuggingBackground": "#2aa198"
},
```

Whether the following code can removed or changed in `extension.ts`  file of your plugin?

```
// When configuration is changed, resume web server.
vscode.workspace.onDidChangeConfiguration(() => {
    resumeServer();
    vscode.window.showInformationMessage("Resume the Web Server.");
 });
```

**Comment by YuichiNukiyama** [comment]
I see. I will add isWatchConfiguration option.
If you set this option, this extension will not resume web server.

**Comment by jing2si** [comment]
Thanks, you can add this config into README
